[package]
name = "niubi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.1"
num="0.4.0"

[dev-dependencies]
assert_approx_eq = "1.1.0"